export {default as Home} from './News.svg';
export {default as Search} from './Search.svg';
export {default as Bookmark} from './Star.svg';
export {default as HomeInactive} from './News-2.svg';
export {default as SearchInactive} from './Search-2.svg';
export {default as BookmarkInactive} from './Star-2.svg';
export {default as UserInactive} from './User-2.svg';
export {default as HomeActiveGreen} from './News-3.svg';
export {default as SearchActiveGreen} from './Search-3.svg';
export {default as BookmarkActiveGreen} from './Star-3.svg';
export {default as UserActiveGreen} from './User.svg';
export {default as SearchIconBlue} from './search-4.svg';
export {default as SearchIconWhite} from './search-5.svg';
export {default as PersonFillWhite} from './person-fill.svg';
// export {default as DeleteIcon} from './Delete.svg';
