name: Android CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-android:
    name: Build & Deploy Android
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.7

      - name: Install Dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: '35.0.0'
          target: 'android-35'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build with Fastlane
        run: |
          cd android
          fastlane build

      - name: Upload to Google Play
        run: |
          cd android
          fastlane upload_to_playstore
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          # GOOGLE_PLAY_PACKAGE_NAME: ${{ secrets.GOOGLE_PLAY_PACKAGE_NAME }}
