name: iOS CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-ios:
    name: Build & Deploy iOS
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.7

      - name: Install Dependencies
        run: npm install

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Fastlane iOS Beta
        run: cd ios && fastlane beta
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID: "appleDeveloperEmail@icloud.com" 처럼 직접 써도 되지만 보안상 secrets 사용 권장
          # FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          # FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
