name: PLANE-ACCIDENT-FINDER-FRONTEND

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node dependencies
        run: npm install

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build React Native APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Rename APK file
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +'%y%m%d')
          APK_SOURCE="android/app/build/outputs/apk/release/app-release.apk"
          APK_TARGET="android/app/build/outputs/apk/release/plane-accident-finder-${DATE}-${SHORT_COMMIT_HASH}.apk"
          if [ -f "$APK_SOURCE" ]; then
            mv "$APK_SOURCE" "$APK_TARGET"
          else
            echo "APK source file not found: $APK_SOURCE"
            exit 1
          fi

      - name: Download existing JSON file from Synology NAS
        env:
          SYNOSSH_HOST: ${{ secrets.SYNOSSH_HOST }}
          SYNOSSH_USERNAME: ${{ secrets.SYNOSSH_USERNAME }}
          SYNOSSH_PASSWORD: ${{ secrets.SYNOSSH_PASSWORD }}
        run: |
          JSON_PATH="android/app/build/outputs/apk/release/plane-accident-finder-files.json"
          sshpass -p "$SYNOSSH_PASSWORD" scp -o StrictHostKeyChecking=no -P 2022 \
            $SYNOSSH_USERNAME@$SYNOSSH_HOST:/volume1/web/plane-accident-finder/downloads/plane-accident-finder-files.json "$JSON_PATH" || echo '{"files": []}' > "$JSON_PATH"

      - name: Update JSON file with build info
        run: |
          set -e
          FULL_COMMIT_HASH=$(git rev-parse HEAD)
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +'%y%m%d')
          APK_NAME="plane-accident-finder-${DATE}-${SHORT_COMMIT_HASH}.apk"
          FILE_PATH="android/app/build/outputs/apk/release/${APK_NAME}"
          FILE_SIZE=$(stat -c%s "$FILE_PATH")
          JSON_PATH="android/app/build/outputs/apk/release/plane-accident-finder-files.json"
          COMMIT_LINK="https://github.com/${GITHUB_REPOSITORY}/commit/${FULL_COMMIT_HASH}"
          EXISTING_JSON=$(cat "$JSON_PATH")
          UPDATED_JSON=$(echo "$EXISTING_JSON" | jq --arg apk_name "$APK_NAME" \
                                                     --arg file_size "$FILE_SIZE" \
                                                     --arg build_date "$DATE" \
                                                     --arg commit_link "$COMMIT_LINK" \
                                                     --arg full_commit_hash "$FULL_COMMIT_HASH" \
            '.files += [{"apk_name": $apk_name, "file_size": $file_size, "build_date": $build_date, "commit_link": $commit_link, "full_commit_hash": $full_commit_hash}]')
          echo "$UPDATED_JSON" > "$JSON_PATH"
          echo "Updated JSON file:"
          cat "$JSON_PATH"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plane-accident-finder
          path: |
            android/app/build/outputs/apk/release/plane-accident-finder-*.apk
            android/app/build/outputs/apk/release/plane-accident-finder-files.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: plane-accident-finder
          path: android/app/build/outputs/

      - name: Verify JSON file
        run: |
          cat android/app/build/outputs/apk/release/plane-accident-finder-files.json

      - name: Upload APK and JSON to Synology NAS
        env:
          SYNOSSH_HOST: ${{ secrets.SYNOSSH_HOST }}
          SYNOSSH_USERNAME: ${{ secrets.SYNOSSH_USERNAME }}
          SYNOSSH_PASSWORD: ${{ secrets.SYNOSSH_PASSWORD }}
        run: |
          sshpass -p "$SYNOSSH_PASSWORD" scp -o StrictHostKeyChecking=no -P 2022 \
            android/app/build/outputs/apk/release/plane-accident-finder-*.apk \
            android/app/build/outputs/apk/release/plane-accident-finder-files.json \
            $SYNOSSH_USERNAME@$SYNOSSH_HOST:/volume1/web/plane-accident-finder/downloads/
