name: PLANE-ACCIDENT-FINDER-FRONTEND

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_BUILD_TOOLS_VERSION: 35.0.0
      ANDROID_COMPILE_SDK: 35
      ANDROID_TARGET_SDK: 34
      ANDROID_MIN_SDK: 24
      ANDROID_NDK_VERSION: 27.1.12297006
      KOTLIN_VERSION: 2.0.21

    steps:
      # 1) 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Node.js / NPM 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) .env 파일 생성 (기밀 정보는 GitHub Secrets에 저장 후 ENV에 할당)
      - name: Create .env file from secret
        run: echo "${{ secrets.ENV }}" > .env

      # 4) 프로젝트 종속성 설치
      - name: Install Node dependencies
        run: npm install

      # 5) 추가 패키지(sshpass, jq) 설치
      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      # 6) Android SDK 환경 변수 설정
      - name: Setup Android SDK Environment Variables
        run: |
          echo "ANDROID_BUILD_TOOLS_VERSION=$ANDROID_BUILD_TOOLS_VERSION" >> $GITHUB_ENV
          echo "ANDROID_COMPILE_SDK=$ANDROID_COMPILE_SDK" >> $GITHUB_ENV
          echo "ANDROID_TARGET_SDK=$ANDROID_TARGET_SDK" >> $GITHUB_ENV
          echo "ANDROID_MIN_SDK=$ANDROID_MIN_SDK" >> $GITHUB_ENV
          echo "ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION" >> $GITHUB_ENV

      # 7) JDK 17 + Gradle 캐싱
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 8) gradlew 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      # 9) 디버그 keystore 생성/저장 (Base64로 GitHub Secret에 저장했다가 디코딩)
      - name: Decode and save debug.keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 --decode > android/app/debug.keystore

      # 10) React Native APK 빌드 (Release)
      - name: Build React Native APK
        working-directory: android
        run: ./gradlew assembleRelease

      # 11) 빌드된 APK 파일 이름 변경
      - name: Rename APK file
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +'%y%m%d')
          APK_SOURCE="android/app/build/outputs/apk/release/app-release.apk"
          APK_TARGET="android/app/build/outputs/apk/release/plane-accident-finder-${DATE}-${SHORT_COMMIT_HASH}.apk"
          if [ -f "$APK_SOURCE" ]; then
            mv "$APK_SOURCE" "$APK_TARGET"
          else
            echo "APK source file not found: $APK_SOURCE"
            exit 1
          fi

      # 12) 로컬에 JSON 파일(plane-accident-finder-cicd-history.json) 준비
      - name: Ensure plane-accident-finder-cicd-history.json exists
        run: |
          JSON_PATH="android/app/build/outputs/apk/release/plane-accident-finder-cicd-history.json"
          mkdir -p $(dirname "$JSON_PATH")
          if [ ! -f "$JSON_PATH" ]; then
            echo '{"files": []}' > "$JSON_PATH"
          fi

      # 13) NAS에서 기존 JSON 다운로드 시도 / 실패 시 로컬 파일 그대로 사용
      - name: Download or initialize JSON file from Synology NAS
        env:
          SYNOSSH_HOST: ${{ secrets.SYNOSSH_HOST }}
          SYNOSSH_USERNAME: ${{ secrets.SYNOSSH_USERNAME }}
          SYNOSSH_PASSWORD: ${{ secrets.SYNOSSH_PASSWORD }}
        run: |
          JSON_PATH="android/app/build/outputs/apk/release/plane-accident-finder-cicd-history.json"
          if ! sshpass -p "$SYNOSSH_PASSWORD" scp -o StrictHostKeyChecking=no -P 2022 \
            $SYNOSSH_USERNAME@$SYNOSSH_HOST:/volume1/web/plane-accident-finder/downloads/plane-accident-finder-cicd-history.json "$JSON_PATH"; then
            echo "No existing JSON on NAS. Using local file."
          fi

      # 14) JSON 파일 업데이트 (빌드 정보 추가)
      - name: Update JSON file with build info
        run: |
          set -e
          FULL_COMMIT_HASH=$(git rev-parse HEAD)
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          DATE=$(date +'%y%m%d')
          APK_NAME="plane-accident-finder-${DATE}-${SHORT_COMMIT_HASH}.apk"
          FILE_PATH="android/app/build/outputs/apk/release/${APK_NAME}"
          FILE_SIZE=$(stat -c%s "$FILE_PATH")
          JSON_PATH="android/app/build/outputs/apk/release/plane-accident-finder-cicd-history.json"
          COMMIT_LINK="https://github.com/${GITHUB_REPOSITORY}/commit/${FULL_COMMIT_HASH}"

          UPDATED_JSON=$(jq --arg apk_name "$APK_NAME" \
                            --arg file_size "$FILE_SIZE" \
                            --arg build_date "$DATE" \
                            --arg commit_link "$COMMIT_LINK" \
                            --arg full_commit_hash "$FULL_COMMIT_HASH" \
            '.files += [{"apk_name": $apk_name, "file_size": $file_size, "build_date": $build_date, "commit_link": $commit_link, "full_commit_hash": $full_commit_hash}]' \
            "$JSON_PATH")

          echo "$UPDATED_JSON" > "$JSON_PATH"
          echo "Updated JSON file:"
          cat "$JSON_PATH"

      # 15) 빌드 결과물(APK + JSON) 업로드 (Artifact)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plane-accident-finder
          path: |
            android/app/build/outputs/apk/release/plane-accident-finder-*.apk
            android/app/build/outputs/apk/release/plane-accident-finder-cicd-history.json

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      # 1) 아티팩트 다운로드 (plane-accident-finder)
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: plane-accident-finder
          path: android/app/build/outputs/

      # 2) 디버그: 실제로 어떤 폴더 구조로 풀렸는지 확인
      - name: List downloaded structure
        run: ls -alR android/app/build/outputs

      # 3) JSON 파일을 검증
      #    (위의 'ls -alR' 결과를 보고, 파일이 어디 위치했는지에 맞춰 경로 수정)
      - name: Verify JSON file
        run: |
          cat android/app/build/outputs/plane-accident-finder-cicd-history.json

      # 4) Synology NAS로 APK & JSON 업로드
      - name: Upload APK and JSON to Synology NAS
        env:
          SYNOSSH_HOST: ${{ secrets.SYNOSSH_HOST }}
          SYNOSSH_USERNAME: ${{ secrets.SYNOSSH_USERNAME }}
          SYNOSSH_PASSWORD: ${{ secrets.SYNOSSH_PASSWORD }}
        run: |
          # 실제 파일 구조가 'android/app/build/outputs/plane-accident-finder-*.apk' 일 수도 있음
          sshpass -p "$SYNOSSH_PASSWORD" scp -o StrictHostKeyChecking=no -P 2022 \
            android/app/build/outputs/plane-accident-finder-*.apk \
            android/app/build/outputs/plane-accident-finder-cicd-history.json \
            $SYNOSSH_USERNAME@$SYNOSSH_HOST:/volume1/web/plane-accident-finder/downloads/
